name: dino-client-master
version: "master"
summary: dino (XMPP Client)
description: |
  Modern Jabber/XMPP Client using GTK+/Vala

base: core18
confinement: devmode

apps:
  dino-client:
    command: desktop-launch dino
    plugs:
    - x11
    - wayland # let it run on wayland, because it's gtk3 so it should be fine
    - desktop # needed for a lot of gtk3 and glib interaction with the host system
    - desktop-legacy # needed for accessibility tools IIRC
    - network-bind

parts:
  desktop-gtk3:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    plugin: make
    make-parameters: ["FLAVOR=gtk3"]
    build-packages:
      - build-essential
      - libgtk-3-dev
    stage-packages:
      - libxkbcommon0  # XKB_CONFIG_ROOT
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libgtk-3-0
      - libgdk-pixbuf2.0-0
      - libglib2.0-bin
      - libgtk-3-bin
      - unity-gtk3-module
      - libappindicator3-1
      - locales-all
      - xdg-user-dirs
      - ibus-gtk3
      - libibus-1.0-5
      - fcitx-frontend-gtk3
  dino-client:
    after: [desktop-gtk3]
    plugin: cmake
    source-type: git
    source-branch: master
    source-depth: 1
    source: https://github.com/dino/dino.git

    build-packages:
      - build-essential
      - cmake
      - fuse
      - git
      - libgcrypt20-dev
      - libgdk-pixbuf2.0-dev
      - libgee-0.8-dev
      - libgpgme-dev
      - libgtk-3-dev
      - libqrencode-dev
      - libsoup2.4-dev
      - libsqlite3-dev
      - snapd
      - squashfuse
      - valac

    stage-packages:
      - zlib1g
      - libassuan0
      - libatk1.0-0
      - libatk-bridge2.0-0
      - libatspi2.0-0
      - libcairo2
      - libcairo-gobject2
      - libdatrie1
      - libepoxy0
      - libfontconfig1
      - libgdk-pixbuf2.0-0
      - libgee-0.8-2
      - libgpgme11
      - libgraphite2-3
      - libgtk-3-0
      - libharfbuzz0b
      - libicu60
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libpangoft2-1.0-0
      - libpixman-1-0
      - libpng16-16
      - libqrencode3
      - libsoup2.4-1
      - libthai0
      - libwayland-client0
      - libwayland-cursor0
      - libwayland-egl1
      - libx11-6
      - libxau6
      - libxcb1
      - libxcb-render0
      - libxcb-shm0
      - libxcomposite1
      - libxcursor1
      - libxdamage1
      - libxdmcp6
      - libxext6
      - libxfixes3
      - libxi6
      - libxinerama1
      - libxkbcommon0
      - libxml2
      - libxrandr2
      - libxrender1
